---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  annotations:
    argocd.argoproj.io/sync-options: PruneLast=true
    argocd.argoproj.io/sync-wave: '-2'
  creationTimestamp:
  name: poc-apps
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  description: poc-apps project
  destinations:
    - namespace: '*'
      server: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos: ['*']
status: {}
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '0'
  creationTimestamp:
  name: poc-apps
  namespace: argocd
spec:
  generators:
    - git:
        files:
          - path: apps/poc-apps/**/config.yaml
        repoURL: https://GIT-SERVER-URL/ORG/REPO.git
        requeueAfterSeconds: 20
        revision: ''
        template:
          spec:
            project: ''
            destination: {}
            source:
              path: '{{ srcPath }}'
              repoURL: '{{ srcRepoURL }}'
              targetRevision: '{{ srcTargetRevision }}'
    - git:
        files:
          - path: apps/poc-apps/**/config_dir.yaml
        repoURL: https://GIT-SERVER-URL/ORG/REPO.git
        requeueAfterSeconds: 20
        revision: ''
        template:
          spec:
            project: ''
            destination: {}
            source:
              directory:
                exclude: '{{ exclude }}'
                include: '{{ include }}'
                jsonnet: {}
                recurse: true
              path: '{{ srcPath }}'
              repoURL: '{{ srcRepoURL }}'
              targetRevision: '{{ srcTargetRevision }}'
    - git:
        files:
          - path: apps/poc-apps/**/config_helm.yaml
        repoURL: https://GIT-SERVER-URL/ORG/REPO.git
        requeueAfterSeconds: 20
        revision: ''
        template:
          spec:
            project: ''
            destination: {}
            source:
              helm:
                valueFiles: ['{{ valueFiles }}']
              path: '{{ srcRepoPath }}'
              repoURL: '{{ srcRepoURL }}'
              targetRevision: '{{ srcTargetRevision }}'
  syncPolicy: {}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: '{{ appName }}'
      name: poc-apps-{{ userGivenName }}
      namespace: argocd
    spec:
      destination:
        namespace: '{{ destNamespace }}'
        server: '{{ destServer }}'
      ignoreDifferences:
        - group: argoproj.io
          jsonPointers: [/status]
          kind: Application
      project: poc-apps
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
status: {}
